### ISSUE TITLE
/lib directory is not found in the src code

### ISSUE THREAD

**Issue by ZirakZaheer** [lsds/TaLoS#1]
Hi,

Thanks for making your work public. I was trying to compile this but it turns out that 
/TaLoS/src/libressl-2.4.1/lib is missing. I am able to compile /TaLoS/src/libressl-2.4.1/crypto folder fine.

Can you please tell if I am doing something right?

**Comment by schaars** [comment]
Hi.

The `libressl-2.4.1/lib` directory is created when running the install target of the Makefile (either `Makefile.sgx` or `Makefile.nosgx` in `libressl-2.4.1/crypto`). In addition to creating the directory it also populates it with symbolic links to the compiled libraries:
```
mkdir -p ../lib
ln -sfn ../crypto/libenclave.so ../lib/libssl.so
ln -sfn ../crypto/libenclave.so ../lib/libcrypto.so
ln -sfn ../crypto/libenclave.a ../lib/libssl.a
ln -sfn ../crypto/libenclave.a ../lib/libcrypto.a
```

For a quick test you can use the Docker image. You can also follow the steps listed in the `Dockerfile` file.

**Comment by ZirakZaheer** [comment]
Thanks! :)

Can I use this project as an SGX compatible equivalent version of OpenSSL? i.e using the openssl api inside the trusted code?

**Comment by schaars** [comment]
Yes. TaLoS executes LibreSSL in an enclave, which provides the same interface as OpenSSL. You have access to the LibreSSL functionalities from inside the enclave.
