### ISSUE TITLE
Problem with the README

### ISSUE THREAD

**Issue by sihussain2** [lsds/TaLoS#10]
The SEcure Processing of TLS communication segment of the README may have a typo.

void tls_processing_register_ssl_write_processing_cb(void (*cb)(const SSL*, char*, unsigned int)): register the callback that will be called by do_ssl3_write() in ssl/s3_pkt.c when data is read from the TLS connection socket;

Shouldnt this be 

....called by do_ssl3_write() in ssl/s3_pkt.c when data is written to the TLS connection socket;

**Comment by schaars** [comment]
Thank you for your report. We will soon upload an updated version of the readme file.

**Comment by schaars** [comment]
Commit 41584e3 resolves this issue.
