### ISSUE TITLE
memcpy warning when compiling TaLoS

### ISSUE THREAD

**Issue by dorflex150mg** [lsds/TaLoS#19]
When compiling TaLoS in there is a warning in HW mode from file `asn1/a_bitstr.c`

`In file included from /usr/include/string.h:494:0,`
`                 from ../include/compat/string.h:16,`
`                 from asn1/a_bitstr.c:60:`
`In function ‘memcpy’,`
`    inlined from ‘i2c_ASN1_BIT_STRING’ at asn1/a_bitstr.c:121:2:`
`/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:10: error: ‘__builtin_memcpy’: specified` `size between 18446744071562067968 and 18446744073709551615 exceeds maximum object` `size 9223372036854775807 [-Werror=stringop-overflow=]`
`   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));`
`          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ `

**Comment by plaublin** [comment]
Hi

This is apparently related to the newer versions of gcc. Besides removing `-Werror` We did not find a fix yet.

**Comment by plaublin** [comment]
Fixed by a5b5d90
