### ISSUE TITLE
Some memory not freed

### ISSUE THREAD

**Issue by InfiniteSamuel** [lsds/TaLoS#4]
I recently discovered a bug. In `/src/talos/patch/tasn_fre.c.patch::24`, you have a #else macro, which is unnecessary.  The code should be like this:
```
static void smart_free(void* ptr) {
#ifdef COMPILE_WITH_INTEL_SGX
	if (sgx_is_within_enclave(ptr, 1)) {
//#else
#endif
		free(ptr);
//#endif
#ifdef COMPILE_WITH_INTEL_SGX
	} else {
		ocall_free(ptr);
	}
#endif
}
```
Otherwise the ptr will not be freed.

**Comment by InfiniteSamuel** [comment]
Actually if you decrease the `<HeapMaxSize>` by about 256 times in the `enclave.config.xml`, you will discover this bug soon enough.

**Comment by schaars** [comment]
Thank you for discovering this bug. Commit 1332eec4f4fbc1f12584571128274946d341a0e0 fixes this issue.
