### ISSUE TITLE
Unable to establish SSL connection

### ISSUE THREAD

**Issue by tiepnv-viosoft** [lsds/TaLoS#5]
Hi,
I'm planning to evaluate the TaLoS with Nginx. However, when I accessed the web pages, I had the following issue:

```
$ wget --no-check-certificate https://localhost:7778/index.html
--2018-01-19 02:47:20--  https://localhost:7778/index.html
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:7778... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:7778... connected.
Unable to establish SSL connection.
```
At the same time, the nginx stopped with the error "Segmentation fault (core dumped)".
Could you let me know the reason why the SSL connection failed?

Thanks!

**Comment by schaars** [comment]
Hi

Thank you for raising this issue. This is due to a bug in the `ssl_ctx_info_fake_cb(const SSL *ssl, int type, int val)` function in `ssl/ssl_lib.c`. This function has not been updated correctly after we changed how the shadow structures mechanism stores objects.

This bug is fixed in commit 1ed1a18.

**Comment by gmatesunny** [comment]
How did you build nginx, I am getting undefined references for sgx related function while doing make for nginx.

**Comment by tiepnv-viosoft** [comment]
Hi gmatesunny, I followed the guide on the github. Did you link your sgx_sdk in the objs/Makefile?

> in objs/nginx, for the LINK phase, update the following line with the correct path to libssl.a and libcrypto.a and add -lsgx_urts -lsgx_uae_service. Depending on how you compiled TaLoS, you may want to change -lsgx_urts -lsgx_uae_service (real hardware) to -lsgx_urts_sim -lsgx_uae_service_sim (simulator).

**Comment by gmatesunny** [comment]
I resolved this problem but got to stuck with the following segmentation fault/enclave identification error. 

https://github.com/lsds/TaLoS/issues/8
