### ISSUE TITLE
Nginx unable to run

### ISSUE THREAD

**Issue by gmatesunny** [lsds/TaLoS#8]
I am able to build nginx with dynamic library and I followed the readme.md but on running the nginx binary it fails to start. Please see the figure to understand more.
![image](https://user-images.githubusercontent.com/17284495/37234051-00310ef8-23f6-11e8-81ae-fdc04c4779fd.png)

Could someone please help me to run nginx with TaLoS.

**Comment by gmatesunny** [comment]
If I keep the enclave.signed.so at same directory as nginx binary, it results in segmentation fault.

roshan@bolt:~/talos/src/nginx-1.11.0/install/sbin$ pwd
```
/home/roshan/talos/src/nginx-1.11.0/install/sbin
roshan@bolt:~/talos/src/nginx-1.11.0/install/sbin$ ls -a
.  ..  enclave.signed.so  nginx
roshan@bolt:~/talos/src/nginx-1.11.0/install/sbin$ ./nginx 
Segmentation fault
```

**Comment by tiepnv-viosoft** [comment]
This is some change I modified in the "nginx-1.11.0/objs/Makefile":

```
--- nginx-1.11.0/objs/Makefile	2018-03-12 01:40:28.899019963 -0700
+++ nginx-1.11.0-std/objs/Makefile	2018-03-12 01:41:58.831507135 -0700
@@ -9,7 +9,7 @@
 	-I src/event \
 	-I src/event/modules \
 	-I src/os/unix \
-	-I /home/administrator/nginx_talos_release/TaLoS//src/libressl-2.4.1//.openssl/include \
+	-I /home/administrator/nginx_talos_release/TaLoS/src/libressl-2.4.1/include \
 	-I objs \
 	-I src/http \
 	-I src/http/modules
@@ -76,7 +76,6 @@
 	src/os/unix/ngx_linux.h \
 	src/event/ngx_event_openssl.h \
 	src/core/ngx_regex.h \
-	/home/administrator/nginx_talos_release/TaLoS//src/libressl-2.4.1//.openssl/include/openssl/ssl.h \
 	objs/ngx_auto_config.h
 
 
@@ -84,7 +83,7 @@
 	-I src/event \
 	-I src/event/modules \
 	-I src/os/unix \
-	-I /home/administrator/nginx_talos_release/TaLoS//src/libressl-2.4.1//.openssl/include \
+	-I /home/administrator/nginx_talos_release/TaLoS/src/libressl-2.4.1/include \
 	-I objs
 
 
@@ -345,7 +344,7 @@
 	objs/src/http/modules/ngx_http_upstream_keepalive_module.o \
 	objs/src/http/modules/ngx_http_upstream_zone_module.o \
 	objs/ngx_modules.o \
-	-ldl -lpthread -lcrypt -lpcre /home/administrator/nginx_talos_release/TaLoS//src/libressl-2.4.1//.openssl/lib/libssl.a /home/administrator/nginx_talos_release/TaLoS//src/libressl-2.4.1//.openssl/lib/libcrypto.a -ldl -lz \
+	-ldl -lpthread -lcrypt -lpcre /home/administrator/nginx_talos_release/TaLoS/src/libressl-2.4.1/lib/libssl.a /home/administrator/nginx_talos_release/TaLoS/src/libressl-2.4.1/lib/libcrypto.a -L /home/administrator/nginx_talos_release/intel/sgxsdk/sdk_libs -lsgx_urts_sim -lsgx_uae_service_sim -ldl -lz \
 	-Wl,-E
 	
 
@@ -1171,75 +1170,69 @@
 		src/http/modules/ngx_http_upstream_zone_module.c
 
 
-/home/administrator/nginx_talos_release/TaLoS//src/libressl-2.4.1//.openssl/include/openssl/ssl.h:	objs/Makefile
-	cd /home/administrator/nginx_talos_release/TaLoS//src/libressl-2.4.1/ \
-	&& if [ -f Makefile ]; then $(MAKE) clean; fi \
-	&& ./config --prefix=/home/administrator/nginx_talos_release/TaLoS//src/libressl-2.4.1//.openssl no-shared  \
-	&& $(MAKE) \
-	&& $(MAKE) install_sw LIBDIR=lib
 
 
 manpage:	objs/nginx.8
```

Hope it helps you.

**Comment by gmatesunny** [comment]
Where did you place enclave.signed.so ? Could you tell the path of it ? In my system I created a link here:
/home/roshan/talos/src/nginx-1.11.0/enclave.signed.so that points to the /home/roshan/talos/src/libressl-2.4.1/crypto/enclave.signed.so

**Comment by tiepnv-viosoft** [comment]
My system is the same yours. However, I only test in sgx simulator mode (-lsgx_urts_sim -lsgx_uae_service_sim).

**Comment by gmatesunny** [comment]
I am also only testing the sim mode.

**Comment by gmatesunny** [comment]
I tried to see what causes segmentation fault and this is the output:
roshan@bolt:~/talos/src/nginx-1.11.0$ gdb ./install/sbin/nginx
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./install/sbin/nginx...done.
(gdb) run
Starting program: /home/roshan/talos/src/nginx-1.11.0/install/sbin/nginx 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff72f5895 in _create_enclave(bool, int, _se_file_t&, _le_prd_css_file_t*, unsigned char (*) [1024], int*, unsigned long*, _sgx_misc_attribute_t*) ()
   from /home/roshan/sgxsdk/lib64/libsgx_urts_sim.so
(gdb)

**Comment by gmatesunny** [comment]
This time I did static linking.

**Comment by gmatesunny** [comment]
I was able to solve the problem by downgrading to sgxsdk version 1.9.
Please add this information in readme.md and also there is typo for ssh instead of ssl in readme.md
