### ISSUE TITLE
Hi, I get the the errors when I compile Nginx with talos. Please help me. 

### ISSUE THREAD

**Issue by baoyibao99** [lsds/TaLoS#9]
/home/yibao/projects/TaLoS/src/libressl-2.4.1/ssl/.libs/libssl.a(s3_pkt.o): In function `do_ssl3_write':
/home/yibao/projects/TaLoS/src/libressl-2.4.1/ssl/s3_pkt.c:723: undefined reference to `tls_processing_ssl_write'
/home/yibao/projects/TaLoS/src/libressl-2.4.1/ssl/.libs/libssl.a(s3_pkt.o): In function `ssl3_read_bytes':
/home/yibao/projects/TaLoS/src/libressl-2.4.1/ssl/s3_pkt.c:984: undefined reference to `tls_processing_ssl_read'
/home/yibao/projects/TaLoS/src/libressl-2.4.1/ssl/.libs/libssl.a(ssl_lib.o): In function `SSL_free':
/home/yibao/projects/TaLoS/src/libressl-2.4.1/ssl/ssl_lib.c:766: undefined reference to `tls_processing_free_connection'
/home/yibao/projects/TaLoS/src/libressl-2.4.1/ssl/.libs/libssl.a(ssl_lib.o): In function `SSL_new':
/home/yibao/projects/TaLoS/src/libressl-2.4.1/ssl/ssl_lib.c:521: undefined reference to `tls_processing_new_connection'
/home/yibao/projects/TaLoS/src/libressl-2.4.1/crypto/.libs/libcrypto.a(libcrypto_la-bio_lib.o): In function `BIO_int_ctrl':
/home/yibao/projects/TaLoS/src/libressl-2.4.1/crypto/bio/bio_lib.c:590: undefined reference to `tls_processing_set_ssl_type'
collect2: error: ld returned 1 exit status
Makefile:491: recipe for target 'openssl' failed
make[4]: *** [openssl] Error 1
make[4]: Leaving directory '/home/yibao/projects/TaLoS/src/libressl-2.4.1/apps/openssl'
Makefile:363: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/yibao/projects/TaLoS/src/libressl-2.4.1/apps'
Makefile:453: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/yibao/projects/TaLoS/src/libressl-2.4.1'
objs/Makefile:1175: recipe for target '/home/yibao/projects/TaLoS/src/libressl-2.4.1//.openssl/include/openssl/ssl.h' failed
make[1]: *** [/home/yibao/projects/TaLoS/src/libressl-2.4.1//.openssl/include/openssl/ssl.h] Error 2
make[1]: Leaving directory '/home/yibao/projects/TaLoS/src/nginx-1.11.0'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by schaars** [comment]
Hi

It seems like you are compiling LibreSSL using the Makefile in the `libressl-2.4.1` directory. The LibreSSL `apps` have not been modified to compile with TaLoS. Instead, you need compile TaLoS separately, before compiling Nginx, and then edit Nginx Makefile (in `objs/Makefile`) not to compile LibreSSL, as specified in the [readme](https://github.com/lsds/TaLoS#using-talos-with-nginx).

**Comment by baoyibao99** [comment]
Wonderful,  thanks!
